export const CREATE_REPORT_SUCCESS = " CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_ERROR = "CREATE_REPORT_ERROR";
export const CREATE_REPORT_REQUEST = "CREATE_REPORT_REQUEST";

export const GET_DOCTOR_SUCCESS = " GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_ERROR = "GET_DOCTOR_ERROR";
export const GET_DOCTOR_REQUEST = "GET_DOCTOR_REQUEST";

export const GET_APPOINTMENT_SUCCESS = " GET_APPOINTMENT_SUCCESS";
export const GET_APPOINTMENT_ERROR = "GET_APPOINTMENT_ERROR";
export const GET_APPOINTMENT_REQUEST = "GET_APPOINTMENT_REQUEST";

export const ADD_PATIENT_SUCCESS = " ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_ERROR = "ADD_PATIENT_ERROR";
export const ADD_PATIENT_REQUEST = "ADD_PATIENT_REQUEST";

export const CREATE_BOOKING_SUCCESS = " CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";
export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";

export const CREATE_PAYMENT_SUCCESS = " CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";
export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";

export const DISCHARGE_PATIENT_SUCCESS = " DISCHARGE_PATIENT_SUCCESS";
export const DISCHARGE_PATIENT_ERROR = "DISCHARGE_PATIENT_ERROR";
export const DISCHARGE_PATIENT_REQUEST = "DISCHARGE_PATIENT_REQUEST";

export const GET_PATIENT_SUCCESS = " GET_PATIENT_SUCCESS";
export const GET_PATIENT_ERROR = "GET_PATIENT_ERROR";
export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";

export const GET_APPOINTMENT_DETAILS_SUCCESS =
  " GET_APPOINTMENT_DETAILS_SUCCESS";
export const GET_APPOINTMENT_DETAILS_ERROR = "GET_APPOINTMENT_DETAILS_ERROR";
export const GET_APPOINTMENT_DETAILS_REQUEST =
  "GET_APPOINTMENT_DETAILS_REQUEST";

export const GET_ALLDATA_SUCCESS = " GET_ALLDATA_SUCCESS";
export const GET_ALLDATA_REQUEST = "GET_ALLDATA_REQUEST";

export const DELETE_APPOINTMENT_SUCCESS = " DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";

export const GET_REPORTS_SUCCESS = " GET_REPORTS_SUCCESS";
export const GET_REPORTS_REQUEST = "GET_REPORTS_REQUEST";

export const ADD_CARE_CONTEXT = "ADD_CARE_CONTEXT";
export const ADD_CARE_CONTEXT_ERROR = "ADD_CARE_CONTEXT_ERROR";

export const REQUEST_CONSENT = "REQUEST_CONSENT";
export const REQUEST_CONSENT_ERROR = "REQUEST_CONSENT_ERROR";
export const REQUEST_CONSENT_SUCCESS = "REQUEST_CONSENT_SUCCESS";
